# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "testing-appliction"
client_id = "3dc135d710f2fe2334b901079c137c2e"
application_url = "https://adidas-nancy-workstation-significance.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://adidas-nancy-workstation-significance.trycloudflare.com/auth/callback",
  "https://adidas-nancy-workstation-significance.trycloudflare.com/auth/shopify/callback",
  "https://adidas-nancy-workstation-significance.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "custom-websit-design-by-nm.myshopify.com"
